### ISSUE TITLE
he instruction position should be either before the question, or at the beginning of the question, at the end of the question, or at the beginning of the answer.

### ISSUE THREAD

**Issue by wac81** [google-deepmind/opro#2]
File "/nvme/opro/opro/optimization/optimize_instructions.py", line 178, in main
    assert instruction_pos in {
AssertionError: The instruction position should be either before the question, or at the beginning of the question, at the end of the question, or at the beginning of the answer.

got error after run：
python optimize_instructions.py --optimizer="gpt-3.5-turbo" --scorer="text-bison" --instruction_pos="Q_beginning" --dataset="gsm8k" --task="train" --palm_api_key="<your_palm_api_key>" --openai_api_key="<your_openai_api_key>"

**Comment by chengrunyang** [comment]
Thanks for catching the typo! I've updated the example command in README. Please change `Q_beginning` to `Q_begin`.

**Comment by wac81** [comment]
thanks
