### ISSUE TITLE
TSP Problem Experimental Code

### ISSUE THREAD

**Issue by georgewanglz2019** [google-deepmind/opro#4]
I recently came across your fascinating research paper on GitHub and was particularly interested in your work related to the Traveling Salesman Problem (TSP). Your approach and findings have significantly piqued my interest, and I am eager to delve deeper into your methodologies and analyses.

However, upon reviewing the repository, I noticed that the experimental code specific to the TSP problem is not available. Could you kindly provide guidance on where I might find the TSP problem experimental code, or would it be possible for you to share it? Having access to this code would greatly enhance my understanding of your work and allow me to explore your innovative solutions further.

Thanks in advance!

Best,
George

**Comment by chengrunyang** [comment]
Thanks George for the heads up! We've added the TSP code to https://github.com/google-deepmind/opro/blob/main/opro/optimization/optimize_tsp.py. Please let us know if you have any questions.
